settings:
  data-provider: FILE # DATABASE

message:
  invalid-vault-identifier: "&cThe given identifier &7'{identifier}' &cdoes not match any registered vault!"
  no-vault-access: "&cYou do not have permission to access this vault."
  successfully-changed-name: "&aYou have successfully changed the vault at position &7{vault-position}&a's name to &7{vault-name}&a."
  deny-response:
    lenght: "&cThe length of the given name does not match the restrictions (3 > length < 16)"
    unknown: "&cThe name could not be changed for an unknown reason, if you believe this is a mistake, contact an Administrator."